Bruno Branca Topic0 6 of html and 1st of css
brunobranca/startup pull request #1
Opened 2016-10-03 21:06 UTC by brunobranca

2016-10-04 15:10 UTC, afiorenza requested changes
Fix the indentation of the files and please alpha order the css rules. Thanks!

2016-10-04 15:10 UTC, afiorenza commented on 00-HTML-CSS-basics/css/ex 2.1.html
> +  <body  style="background-color:#4f5151">
Avoid inline style. Could you move it to `style.css`?

2016-10-04 15:10 UTC, afiorenza commented on 00-HTML-CSS-basics/css/ex 2.1.html
> +<div class="header">
Fix the indentation

2016-10-04 15:10 UTC, afiorenza commented on 00-HTML-CSS-basics/css/style.css
> +
This break line is not needed

2016-10-04 15:10 UTC, afiorenza commented on 00-HTML-CSS-basics/css/style.css
> +.header { text-align:center;
move text-align rule to the next line

2016-10-04 19:30 UTC, afiorenza requested changes
Good job! just a few comments

2016-10-04 19:30 UTC, afiorenza commented on 00-HTML-CSS-basics/css/ex 2.1.html
> +  <body  >
You don't need the space between `body` and `>`

2016-10-04 19:30 UTC, afiorenza commented on 00-HTML-CSS-basics/css/ex 2.1.html
> +<div class="header">
You don't need to wrap the `h1` in a `div`. Just move the class to the `h1`.

2016-10-04 19:30 UTC, afiorenza commented on 00-HTML-CSS-basics/css/ex 2.1.html
> +<div class="header">
Check other places of this same file

2016-10-04 19:30 UTC, afiorenza commented on 00-HTML-CSS-basics/css/ex 2.1.html
> +
Just one break line is okey

2016-10-04 19:30 UTC, afiorenza commented on 00-HTML-CSS-basics/css/ex 2.1.html
> +<div class="footer">
Check indentation

2016-10-04 19:30 UTC, afiorenza commented on 00-HTML-CSS-basics/css/style.css
> +
One break line is okey

2016-10-04 19:30 UTC, afiorenza commented on 00-HTML-CSS-basics/css/style.css
> +   height: 100%;
Alpha order the rules

2016-10-05 18:01 UTC, brunobranca commented on 00-HTML-CSS-basics/css/ex 2.1.html
> +<div class="header">
Checked

2016-10-05 20:41 UTC, brunobranca commented on 00-HTML-CSS-basics/css/ex 2.1.html
> +  <body  style="background-color:#4f5151">
done

2016-10-05 20:41 UTC, brunobranca commented on 00-HTML-CSS-basics/css/style.css
> +
ok

2016-10-05 20:41 UTC, brunobranca commented on 00-HTML-CSS-basics/css/style.css
> +.header { text-align:center;
done

2016-10-05 20:41 UTC, brunobranca commented on 00-HTML-CSS-basics/css/ex 2.1.html
> +  <body  >
done

2016-10-05 20:41 UTC, brunobranca commented on 00-HTML-CSS-basics/css/ex 2.1.html
> +
done

2016-10-05 20:41 UTC, brunobranca commented on 00-HTML-CSS-basics/css/ex 2.1.html
> +<div class="footer">
done

2016-10-05 20:41 UTC, brunobranca commented on 00-HTML-CSS-basics/css/style.css
> +   height: 100%;
done

2016-10-05 20:41 UTC, brunobranca commented on 00-HTML-CSS-basics/css/style.css
> +
ok

2016-10-06 01:54 UTC, afiorenza approved these changes
Good Job! Ready for merge

2016-10-06 17:12 UTC, merged